import "~/styles/globals.css";
import Header from "~/app/(dashboard)/_dashboard_components/header/header";
import FooterNavigation from "~/app/(dashboard)/_dashboard_components/FooterNavigation";


export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" >
        <body className={``}>

            <Header/>
            <div className={'w-screen flex justify-center'}>

        {children}
        <FooterNavigation/>
            </div>
       </body>
        </html>
    );
}
