import "~/styles/globals.css";
import Header from "~/app/(dashboard)/_dashboard_components/header/header";


export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={``}>
        <div className={'flex items-center gap-2'}>
            <Header/>
        {children}
        </div></body>
        </html>
    );
}
