import "~/styles/globals.css";

import localFont from "next/font/local";
import { Toaster } from "sonner";
import StoreProvider from "./_components/providers/Provider";
const neueMontreal=localFont({
    src: '../../public/fonts/NeueMontreal-Regular.woff2',
    variable:'--font-neue',

    preload: true
})
const neueMontrealBold=localFont({
  src: '../../public/fonts/NeueMontreal-Bold.woff2',
  variable:'--font-neue-bold',
  preload: true
})
const rogBold=localFont({
  src: '../../public/fonts/rogbold.otf',
  variable:'--font-rog-bold',
  preload: true
})
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
    <Toaster
        richColors
        position="top-center"
        closeButton
        toastOptions={{

            style:{

                backdropFilter:"blur(20px)",
                background:'transparent',

                color:'white'
            }
        }}
    />

    <StoreProvider>
      <body className={` ${neueMontreal.variable} ${neueMontrealBold.variable} ${rogBold.variable}
      font-primary bg-fixed
bg-gradient-to-br from-[#2e026d] via-[#0e1129] to-[#2e026d]
text-white
min-h-screen
      `}>

      {children}
    </body>
</StoreProvider>
    </html>

  );
}
