import "~/styles/globals.css";

import localFont from "next/font/local";
import Header from "~/app/_components/general/Header";
export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`
      `}>
       <Header/>
        {children}</body>
        </html>
    );
}
