import "~/styles/globals.css";
import Header from "~/app/(gallery)/_gallery_components/header/header";
import FooterNavigation from "~/app/(gallery)/_gallery_components/FooterNavigation";
export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" >
        <body className={``}>

            <Header/>



        {children}
            <div className={'w-screen flex justify-center h-fit'}>
        <FooterNavigation/>
           </div>
       </body>
        </html>
    );
}
